plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/clawbotpi/sites/paulibeauty"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/thank-you"
to = "/thank-you.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]